# Generated by Django 5.0.6 on 2025-04-13 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('github_url', models.URLField(blank=True)),
                ('project_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('deleted', models.BooleanField(default=False)),
                ('drafted', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='projects', to='accounts.techcategory')),
                ('contributors', models.ManyToManyField(blank=True, related_name='contributed_projects', to=settings.AUTH_USER_MODEL)),
                ('technologies_used', models.ManyToManyField(related_name='projects_used_in', to='accounts.skill')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='projects_pr_title_ba614c_idx')],
            },
        ),
    ]
