# Generated by Django 5.0.6 on 2025-08-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventticket_paymenttransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='payment_initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
