# Generated by Django 5.0.6 on 2025-05-05 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_type', models.CharField(choices=[('blog', 'Blog Post'), ('project', 'Project'), ('forum', 'Forum'), ('discussion', 'Discussion'), ('event', 'Event'), ('resource', 'Resource'), ('user', 'User Profile')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('folder', models.CharField(blank=True, max_length=100, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='accounts_bo_user_id_f05c42_idx'), models.Index(fields=['bookmark_type'], name='accounts_bo_bookmar_261fbc_idx'), models.Index(fields=['content_type', 'object_id'], name='accounts_bo_content_f88ab2_idx'), models.Index(fields=['created_at'], name='accounts_bo_created_48f2b3_idx')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
